# Generated by Django 5.1.3 on 2024-12-02 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(unique=True)),
                ('metadata_prefix', models.CharField(default='oai_dc', max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('protocol_version', models.CharField(blank=True, max_length=10, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('earliest_datestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted_record_policy', models.CharField(blank=True, max_length=50, null=True)),
                ('granularity', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_harvest_date', models.DateTimeField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='revistas/covers/')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sin título', max_length=500)),
                ('creator', models.TextField(blank=True, default='Desconocido', null=True)),
                ('subject_es', models.TextField(blank=True, default='Sin tema', null=True)),
                ('subject_en', models.TextField(blank=True, default='No subject', null=True)),
                ('description_es', models.TextField(blank=True, default='No disponible', null=True)),
                ('description_en', models.TextField(blank=True, default='Not available', null=True)),
                ('publisher', models.TextField(blank=True, default='No especificado', null=True)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('language', models.CharField(blank=True, default='Desconocido', max_length=10, null=True)),
                ('source', models.TextField(blank=True, default='Sin Fuente', null=True)),
                ('resource_type', models.TextField(blank=True, default='No especificado', null=True)),
                ('format', models.TextField(blank=True, default='Sin Formato', null=True)),
                ('relation', models.TextField(blank=True, default='Sin Relación', null=True)),
                ('official_link', models.URLField(blank=True, default='Sin enlace oficial', null=True)),
                ('rights', models.TextField(blank=True, default='Sin derechos especificados', null=True)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revistas.revista')),
            ],
        ),
    ]
